set number
syntax on
filetype plugin on
" configure tags for omnicomplete
set tags +=~/.vim/tags/cpp
set tags +=~/.vim/tags/opencv
set tags +=~/.vim/tags/opencv2
" OmniCppComplete
set omnifunc=syntaxcomplete
" Set nicer color for pmenu
highlight Pmenu ctermbg=238 gui=bold
let OmniCpp_NamespaceSearch = 1
let OmniCpp_GlobalScopeSearch = 1
let OmniCpp_ShowAccess = 1
let OmniCpp_ShowPrototypeInAbbr = 1 " show function parameters
let OmniCpp_MayCompleteDot = 1 " autocomplete after .
let OmniCpp_MayCompleteArrow = 1 " autocomplete after ->
let OmniCpp_MayCompleteScope = 1 " autocomplete after ::
let OmniCpp_DefaultNamespaces = ["std", "_GLIBCXX_STD"]
" automatically open and close the popup menu / preview window
au CursorMovedI,InsertLeave * if pumvisible() == 0|silent! pclose|endif
set completeopt=menuone,menu,longest,preview
" Enable TAB as completer
let g:SuperTabDefaultCompletionType = "<C-X><C-O>"
" Conque 
let g:ConqueTerm_FastMode = 0
let g:ConqueTerm_ExecFileKey = '<F11>'
" Easier split navigation
" Use ctrl-[hjkl] to select the active split!
nmap <silent> <c-k> :wincmd k<CR>                                                                                                                       
nmap <silent> <c-j> :wincmd j<CR>                                                                                                                       
nmap <silent> <c-h> :wincmd h<CR>                                                                                                                       
nmap <silent> <c-l> :wincmd l<CR>
" Dedicate a shortcut to compiling latex documents
nmap <silent> <c-r> :!pdflatex %
" Enable python omnicomplete
autocmd FileType python set omnifunc=pythoncomplete#Complete
" Use pdf viewer
command! -complete=file -nargs=1 Rpdf :r !pdftotext -nopgbrk <q-args> -
" Activate astyle for c++ by default
autocmd BufNewFile,BufRead *.cpp set formatprg=astyle\ -T4pb
