" Configure vundle
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

set number
" let Vundle manage plugins
Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/nerdtree'

" Install snipmate
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'
" Install python completion
Plugin 'davidhalter/jedi-vim'

" End Vundle plugin list
call vundle#end()
filetype plugin indent on
" Enable Syntax Highlighting
syntax on
" Enable Plugins
filetype plugin on
" Enable automatic indention
filetype indent on
" Fix backspace error
set backspace=indent,eol,start
" Set color scheme
colorscheme jellybeans
" Set space as leader key
let mapleader = "\<Space>"
" Do some custome mappings
nnoremap <Leader>w :w<CR>
nnoremap <Leader>o :CtrlP<CR>
" Copy & paste to system clipboard with <Space>p and <Space>y
vmap <Leader>y "+y
vmap <Leader>d "+d
nmap <Leader>p "+p
nmap <Leader>P "+P
vmap <Leader>p "+p
vmap <Leader>P "+P
" Go into visual mode with <Space><Space>
nmap <Leader><Leader> V
set tabstop=2
